
// This file is used by Code Analysis to maintain SuppressMessage 
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given 
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateItems(Microsoft.Office.Interop.Outlook.Folder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.CreateMonthSubfolders(Microsoft.Office.Interop.Outlook.Folder)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.CreateSortStores(Microsoft.Office.Interop.Outlook.Application)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.CreateYearStore(Microsoft.Office.Interop.Outlook.NameSpace,System.Int32)~Microsoft.Office.Interop.Outlook.Store")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.DeleteEmptyFolders(Microsoft.Office.Interop.Outlook.Folders,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.DeleteEmptyFolders(Microsoft.Office.Interop.Outlook.Folders,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.DeleteEmptyFolders(Microsoft.Office.Interop.Outlook.Stores)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0105:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateFolder(Microsoft.Office.Interop.Outlook.Folder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0111:Incorrect String.Format usage", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateFolder(Microsoft.Office.Interop.Outlook.Folder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateItems(Microsoft.Office.Interop.Outlook.Folder,System.Int32)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateItems(Microsoft.Office.Interop.Outlook.Stores)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.EnumerateStores(Microsoft.Office.Interop.Outlook.Stores)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.GetFolder(Microsoft.Office.Interop.Outlook.Folder,System.String,System.Int32)~Microsoft.Office.Interop.Outlook.Folder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Usage", "CC0057:Unused parameters", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.GetFolder(Microsoft.Office.Interop.Outlook.Folder,System.String,System.Int32)~Microsoft.Office.Interop.Outlook.Folder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.GetOrMakeFolder(Microsoft.Office.Interop.Outlook.Folder,System.String)~Microsoft.Office.Interop.Outlook.Folder")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.GetOrMakeYearStore(Microsoft.Office.Interop.Outlook.Application,System.Int32)~Microsoft.Office.Interop.Outlook.Store")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.Itemiz(System.Object,Microsoft.Office.Interop.Outlook.Folder,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.Main(System.String[])")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Style", "CC0001:You should use 'var' whenever possible.", Justification = "<Pending>", Scope = "member", Target = "~M:ConsoleApp3.Program.NameSortStores(Microsoft.Office.Interop.Outlook.Application)")]